'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

jest.mock('../crypto-mech-board', () => ({
  buildCryptoMechBoard: jest.fn().mockResolvedValue(null),
}));

jest.mock('../hyperliquid-native-layer', () => ({
  buildNativeFeatureBundle: jest.fn().mockResolvedValue(null),
  recordNativeFeatureSnapshot: jest.fn(),
}));

jest.mock('../signal-validation-recorder', () => ({
  settleValidationRecords: jest.fn().mockResolvedValue({ ok: true }),
}));

const { TradingOrchestrator } = require('../orchestrator');
const watchlist = require('../watchlist');

describe('orchestrator range conviction', () => {
  let tmpDir;
  let watchlistSpy;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'squidrun-orch-rc-'));
    watchlistSpy = jest.spyOn(watchlist, 'isWatched').mockReturnValue(true);
  });

  afterEach(() => {
    watchlistSpy.mockRestore();
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch {}
  });

  test('builds a single-thesis conviction result without synthetic quorum backfill', async () => {
    const orchestrator = new TradingOrchestrator({
      journalPath: path.join(tmpDir, 'trade-journal.db'),
      autoExecuteLiveConsensus: false,
    });
    orchestrator.syncSmartMoneyWatchlist = jest.fn().mockResolvedValue([]);
    orchestrator.runDefiMonitorCycle = jest.fn().mockResolvedValue({
      ok: true,
      checkedAt: new Date().toISOString(),
      positions: [],
      warnings: [],
      telegramAlerts: [],
    });
    orchestrator.evaluatePositionManagement = jest.fn().mockReturnValue({
      managedTickers: [],
      executableDirectives: [],
    });
    orchestrator.maybeAutoExecuteLiveConsensus = jest.fn().mockResolvedValue({
      enabled: false,
      attempted: 0,
      succeeded: 0,
      executions: [],
      skipped: [],
    });
    orchestrator.recordCandidateFeatureSnapshots = jest.fn().mockReturnValue({
      ok: true,
      path: path.join(tmpDir, 'candidate-log.jsonl'),
    });

    const phase = await orchestrator.runConsensusRound({
      date: '2026-04-08T08:57:00.000Z',
      symbols: ['ETH/USD'],
      assetClass: 'crypto',
      strategyMode: 'range_conviction',
      convictionSelection: {
        selectedTicker: 'ETH/USD',
      },
      snapshots: new Map([
        ['ETH/USD', {
          tradePrice: 1820,
          askPrice: 1820.5,
          bidPrice: 1819.5,
        }],
      ]),
      bars: new Map([
        ['ETH/USD', []],
      ]),
      news: [],
      rangeStructures: new Map([
        ['ETH/USD', {
          ok: true,
          currentPrice: 1820,
          floor: 1800,
          ceiling: 1895,
          mid: 1847.5,
          widthPct: 0.0514,
          ceilingRejections: 3,
          floorRejections: 3,
          regime: 'range',
          invalidation: {
            long: 1788,
            short: 1908,
          },
          targets: {
            long: 1895,
            short: 1800,
          },
          setups: {
            long: {
              direction: 'BUY',
              confidence: 0.82,
              edgeDistancePct: 0.004,
              invalidationPrice: 1788,
              targetPrice: 1895,
              rationale: 'Price is pressing the floor with three rejections.',
            },
            short: null,
          },
        }],
      ]),
      portfolioSnapshot: {
        equity: 5000,
        positions: [],
      },
      macroRisk: {
        regime: 'green',
        score: 12,
        reason: 'test regime',
      },
      eventVeto: {
        decision: 'CLEAR',
        eventSummary: 'clear',
        affectedAssets: ['ETH/USD'],
      },
      cryptoMechBoard: {
        symbols: {
          'ETH/USD': {
            tradeFlag: 'trade',
            mechanicalDirectionBias: 'bullish',
          },
        },
      },
      nativeSignals: {
        symbols: {
          'ETH/USD': {},
        },
      },
    });

    expect(phase.consultation.reason).toBe('range_conviction_single_thesis');
    expect(phase.autoGeneratedSignals).toEqual([
      expect.objectContaining({
        agentId: 'builder',
        count: 1,
        mode: 'single_thesis',
      }),
    ]);
    expect(phase.results).toHaveLength(1);
    expect(phase.results[0]).toEqual(expect.objectContaining({
      ticker: 'ETH/USD',
      decision: 'BUY',
      consensus: true,
      agreementCount: 1,
    }));
    expect(phase.results[0].agreeing).toHaveLength(1);
    expect(phase.results[0].agreeing[0].agent).toBe('builder');
    expect(phase.approvedTrades).toHaveLength(1);
    expect(phase.approvedTrades[0].signalLookup).toEqual(expect.objectContaining({
      builder: expect.objectContaining({
        ticker: 'ETH/USD',
        direction: 'BUY',
      }),
    }));
    expect(phase.approvedTrades[0].signalLookup.architect).toBeUndefined();
    expect(phase.approvedTrades[0].signalLookup.oracle).toBeUndefined();
  });
});
