'use strict';

jest.mock('../data-ingestion', () => ({
  normalizeSymbols: jest.fn((symbols = []) => Array.from(new Set((Array.isArray(symbols) ? symbols : [symbols]).map((symbol) => String(symbol).trim().toUpperCase()).filter(Boolean)))),
  getWatchlistSnapshots: jest.fn().mockResolvedValue(new Map([
    ['AAPL', { symbol: 'AAPL', tradePrice: 200, dailyVolume: 1000, dailyClose: 198, previousClose: 198 }],
  ])),
  getHistoricalBars: jest.fn().mockResolvedValue(new Map([
    ['AAPL', [
      { symbol: 'AAPL', close: 195, high: 196, low: 194, volume: 1000 },
      { symbol: 'AAPL', close: 198, high: 199, low: 197, volume: 1200 },
      { symbol: 'AAPL', close: 200, high: 201, low: 199, volume: 1400 },
    ]],
  ])),
  getNews: jest.fn().mockResolvedValue([]),
}));

jest.mock('../executor', () => ({
  getAccountSnapshot: jest.fn().mockResolvedValue({ equity: 10000 }),
  getOpenPositions: jest.fn().mockResolvedValue([]),
}));

jest.mock('../journal', () => ({
  getDb: jest.fn(() => ({ mocked: true })),
  getRecentTrades: jest.fn(() => []),
  recordConsensus: jest.fn(),
}));

jest.mock('../risk-engine', () => ({
  DEFAULT_LIMITS: { maxDrawdownPct: 0.2, maxDailyLossPct: 0.1, maxTradesPerDay: 3, maxOpenPositions: 3, maxPositionPct: 0.05, stopLossPct: 0.03 },
  checkKillSwitch: jest.fn(() => ({ triggered: false, drawdownPct: 0 })),
  checkDailyPause: jest.fn(() => ({ paused: false, dayLossPct: 0 })),
  checkTrade: jest.fn(() => ({ approved: true, violations: [], maxShares: 2, stopLossPrice: 194 })),
}));

jest.mock('../signal-producer', () => ({
  produceSignals: jest.fn(async (agentId, options = {}) => {
    const ticker = (options.symbols || [])[0] || 'AAPL';
    return [{
      ticker,
      direction: agentId === 'builder' ? 'BUY' : 'HOLD',
      confidence: agentId === 'builder' ? 0.64 : 0.55,
      reasoning: `${agentId} fallback`,
      model: `${agentId}-heuristic`,
      timestamp: Date.now(),
    }];
  }),
  registerAllSignals: jest.fn((orchestrator, agentId, signals = []) => {
    return signals.map((signal) => orchestrator.registerSignal(agentId, signal.ticker, signal));
  }),
}));

jest.mock('../consultation-store', () => ({
  DEFAULT_CONSULTATION_TIMEOUT_MS: 60000,
  writeConsultationRequest: jest.fn(() => ({
    requestId: 'consult-live-1',
    path: '/tmp/consult-live-1.json',
    deadline: '2099-03-19T04:00:00.000Z',
    createdAt: '2026-03-19T03:59:00.000Z',
    symbols: ['AAPL'],
  })),
  dispatchConsultationRequests: jest.fn().mockResolvedValue([
    { agentId: 'architect', ok: true },
    { agentId: 'builder', ok: true },
    { agentId: 'oracle', ok: true },
  ]),
  collectConsultationResponses: jest.fn().mockResolvedValue({
    requestId: 'consult-live-1',
    responses: [
      {
        requestId: 'consult-live-1',
        agentId: 'architect',
        signals: [
          { ticker: 'AAPL', direction: 'BUY', confidence: 0.91, reasoning: 'real architect analysis' },
        ],
      },
    ],
    missingAgents: ['builder', 'oracle'],
  }),
}));

const journal = require('../journal');
const signalProducer = require('../signal-producer');
const consultationStore = require('../consultation-store');
const { createOrchestrator } = require('../orchestrator');

describe('orchestrator real consultation flow', () => {
  test('collects real consultation responses first and only falls back for missing agents', async () => {
    const orchestrator = createOrchestrator({
      consultationSender: jest.fn(),
      consultationQuery: jest.fn(),
    });

    const result = await orchestrator.runConsensusRound({
      symbols: ['AAPL'],
      consultationTimeoutMs: 50,
    });

    expect(consultationStore.writeConsultationRequest).toHaveBeenCalled();
    expect(consultationStore.dispatchConsultationRequests).toHaveBeenCalled();
    expect(consultationStore.collectConsultationResponses).toHaveBeenCalled();
    expect(signalProducer.produceSignals).toHaveBeenCalledTimes(2);
    expect(signalProducer.produceSignals).toHaveBeenCalledWith('builder', expect.objectContaining({
      symbols: ['AAPL'],
    }));
    expect(signalProducer.produceSignals).toHaveBeenCalledWith('oracle', expect.objectContaining({
      symbols: ['AAPL'],
    }));
    expect(signalProducer.produceSignals).not.toHaveBeenCalledWith('architect', expect.anything());
    expect(result.consultation).toEqual(expect.objectContaining({
      requestId: 'consult-live-1',
      requestedAgents: ['architect', 'builder', 'oracle'],
      missingAgents: ['builder', 'oracle'],
    }));
    expect(result.autoGeneratedSignals).toEqual(expect.arrayContaining([
      expect.objectContaining({ agentId: 'builder', count: 1 }),
      expect.objectContaining({ agentId: 'oracle', count: 1 }),
    ]));
    expect(journal.recordConsensus).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({
      ticker: 'AAPL',
      architectSignal: expect.objectContaining({ reasoning: 'real architect analysis' }),
      builderSignal: expect.objectContaining({ reasoning: 'builder fallback' }),
      oracleSignal: expect.objectContaining({ reasoning: 'oracle fallback' }),
    }));
  });
});
